[NUI] Add Gallery example
Samsung/Tizen-CSharp-Samples pull request #176
Opened 2020-10-05 11:51 UTC by pkalota

Example of [Tizen.NUI.BaseComponents.FlexContainer](https://samsung.github.io/TizenFX/latest/api/Tizen.NUI.BaseComponents.FlexContainer.html) usage
Used in https://docs.tizen.org/application/dotnet/guides/nui/flexcontainer/

2020-10-21 02:53 UTC, hyunjushin requested changes

2020-10-21 02:53 UTC, hyunjushin commented on Mobile/Gallery/Gallery/Gallery.cs
> +            FlexContainer flexContainer = new FlexContainer();
FlexContainer is depreceded on Tizen 6.0. Please check "Obsolete" keyword before you use it.

  [Obsolete("Deprecated in API8, will be removed in API10. Please use FlexLayout instead!")]

2020-10-21 06:41 UTC, pkalota commented on Mobile/Gallery/Gallery/Gallery.cs
> +            FlexContainer flexContainer = new FlexContainer();
Yes, I'm aware of that FlexContainer is obsolete, but this example is created for https://docs.tizen.org/application/dotnet/guides/nui/flexcontainer/. It is more convenient for user to download and try this, so that's why I decided to store it here. Since flexcontainer is obsolete, is this guide is going to be deleted and therefore we don't need to add this example here?

2020-10-25 23:41 UTC, hyunjushin commented on Mobile/Gallery/Gallery/Gallery.cs
> +            FlexContainer flexContainer = new FlexContainer();
The obsoleted APIs will be removed after 2 versions. We don't recommend using these APIs anymore. So we can remove the sample application.

2020-10-28 13:28 UTC, pkalota commented
FlexContainer is obsolete

2020-10-28 13:28 UTC, closed without merging