[Mobile][NUI] Added NUI flex layout sample
Samsung/Tizen-CSharp-Samples pull request #183
Opened 2020-10-15 09:56 UTC by MathewP1

Flex Layout sample to link to in guide

2020-11-02 02:06 UTC, dasg34 requested changes

2020-11-02 02:06 UTC, dasg34 commented on Mobile/NUIFlexLayout/NUIFlexLayout/NUIFlexLayout.cs
> +            layout.LayoutWithTransition = true;
Do not use `LayoutWithTransition` Property. it is not public API.
```cs
[EditorBrowsable(EditorBrowsableState.Never)]
public bool LayoutWithTransition{get; set;}
```

2020-11-02 02:06 UTC, dasg34 commented on Mobile/NUIFlexLayout/NUIFlexLayout/NUIFlexLayout.cs
> +            layout.LayoutWithTransition = true;
Do not use `LayoutWithTransition` Property. it is not public API.
```cs
[EditorBrowsable(EditorBrowsableState.Never)]
public bool LayoutWithTransition{get; set;}
```

2020-11-02 09:26 UTC, MathewP1 commented
Removed `LayoutWithTransition`
Went back to `tizen60` from `tizen80` to merge with `Samsung:master`

2020-11-02 09:43 UTC, dasg34 approved these changes

2021-01-20 01:48 UTC, dongsug-song commented on Mobile/NUIFlexLayout/NUIFlexLayout/NUIFlexLayout.cs
> +﻿using System;
1. I think copyright comments are required here for public open source code.
could you please copy some from other source code?

2. in c#, pascal case is supposed to be used and for private member, it would be OK to use `_` prefix. However in NUI, we have decided **NOT to use prefix such as `_`, `m`, `p`, and etc.**

- NUI ground rule : https://code.sec.samsung.net/confluence/display/GFX/NUI+Ground+Rule
- NUI coding rule : https://code.sec.samsung.net/confluence/pages/viewpage.action?pageId=191373542
- microsoft naming guide : https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines
- microsoft guide : https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions

could you use **PascalCase** even for private fields?

2021-01-25 02:58 UTC, dongsug-song commented
Hello,
Thank you for your works done.

please check the links below and you can see SVACE, Comments Ratio checking, spelling checking, and etc are required.

https://code.sec.samsung.net/confluence/display/TNET/C%23+Sample+release+process

please check the guides and upload the results (any format would be OK) here.
all the checker hurdles are resolved, then we can merge this PR.
thank you.

2021-03-15 05:02 UTC, merged