[Wearable][XF] Svace fixes.
Samsung/Tizen-CSharp-Samples pull request #245
Opened 2021-05-17 08:40 UTC by akrawczyk2

Fixed Svace defects of following Wearable Xamarin.Forms apps:

1. SpeechToText
2. Calculator
3. NetworkApp
4. TextReader
5. Weather

2021-05-19 23:44 UTC, sgchoi5 approved these changes

2021-05-21 00:54 UTC, sgchoi5 commented on Wearable/Xamarin.Forms/Workout/src/Workout/Workout.csproj
> +﻿<Project Sdk="Tizen.NET.Sdk/1.0.6">
1.1.6 is latest version number

2021-05-21 05:26 UTC, sgchoi5 requested changes
Need to resolve merge conflict

2021-05-21 14:20 UTC, akrawczyk2 commented on Wearable/Xamarin.Forms/Workout/src/Workout/Workout.csproj
> +﻿<Project Sdk="Tizen.NET.Sdk/1.0.6">
updated.

2021-05-24 02:21 UTC, sgchoi5 approved these changes

2021-05-24 03:02 UTC, merged